version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: nickblah/lua:5.2-luarocks-focal
    working_directory: ~/lua-cli
    steps:
      - checkout
      - run:
          name: Install Lua
          command: apt-get update && apt-get install -y lua5.2
      - run:
          name: Install Build Tools
          command: apt-get update && apt-get install -y build-essential
      - run:
          name: Set up Lua environment
          command: |
            mkdir -p $HOME/lua
            mv ./* $HOME/lua
            cd $HOME/lua
      - run:
          name: Install Dependencies
          command: luarocks install luafilesystem

  linter:
    docker:
      - image: nickblah/lua:5.2-luarocks-focal
    working_directory: ~/lua-cli
    steps:
      - checkout
      - run:
          name: Install Build Tools
          command: apt-get update && apt-get install -y build-essential
      - run:
          name: Install LuaCheck
          command: luarocks install luacheck
      - run:
          name: Run Lua Linter
          command: luacheck *.lua
          
  test:
    docker:
      - image: nickblah/lua:5.2-luarocks-focal
    working_directory: ~/lua-cli
    steps:
      - checkout
      - run:
          name: Run Tests
          command: lua ./Test_cooker.lua
          
workflows:
  version: 2
  build:
    jobs:
      - install_dependencies:
          filters:
            branches:
              only:
                - feature/lua
      - linter:
          filters:
            branches:
              only:
                - feature/lua
      - test:
          filters:
            branches:
              only:
                - feature/lua
