# CircleCI configuration file

version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: circleci/ruby:3.0

    working_directory: ~/ruby-cli
    steps:
      - checkout
      - run:
          name: Install Bundler and Gems
          command: |
            gem install bundler
            bundle install
  lint:
    docker:
      - image: circleci/ruby:3.0
    working_directory: ~/ruby-cli
    steps:
      - checkout
      - run:
          name: Install RuboCop
          command: gem install rubocop
      - run:
          name: Run RuboCop
          command: rubocop
  build_and_test:
    docker:
      - image: circleci/ruby:3.0
    working_directory: ~/ruby-cli
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            gem install rspec
            rspec ./Tests/rice_cooker_test.rb

workflows:
  version: 2
  build:
    jobs:
      - install_dependencies:
          filters:
            branches:
              only:
                - feature/ruby
      - lint:
          filters:
            branches:
              only:
                - feature/ruby
      - build_and_test:
          filters:
            branches:
              only:
                - feature/ruby
